### ISSUE TITLE
Support neovim 0.6 (nightly) Diagnostics

### ISSUE THREAD

**Issue by mcchrish** [rktjmp/lush-template#7]
Breaking change in neovim: Diagnostics is refactored and the hl group names have changed.
https://github.com/neovim/neovim/issues/14090#issuecomment-921312955

To preserve backwards compat, the old groups (`LspDiagnostics...`) may need to be linked to the new ones (`Diagnostics...`).

**Comment by rktjmp** [comment]
2410d9310ba6cbfc2769ac7fb2c615fbbee603a4
