### ISSUE TITLE
Consider recent Tree-Sitter additions

### ISSUE THREAD

**Issue by adrian5** [rktjmp/lush-template#8]
A few more syntax groups [have been added](https://github.com/nvim-treesitter/nvim-treesitter/commit/e2b2d2357b227b1d2548b6bfb3506b3a93b9e636#diff-1bed7a757fdaad2919ee0d6dbe7bb4d9e721f15d316080853630c5064b768377).

p.s. New to lush and just getting my feet wet, but impressed already by the structure and live visual feedback!

**Comment by rktjmp** [comment]
Sounds good, I'll try to get around to it. Thanks for the heads up.

**Comment by rktjmp** [comment]
Fixed by @adrian5 in #9!
